packages:
  - packages/core
  - packages/types
  - packages/mcp-docs-server
  - packages/mcp
  - packages/docs
  - packages/server
  - packages/create-ai-kit
  - packages/client-kit
  - packages/rag

onlyBuiltDependencies:
  - esbuild
  - protobufjs
  - sqlite3
