import type { OpenAPIV3 } from "openapi-types";

export interface SwaggerDocumentConfig {
  title: string;
  version: string;
  description?: string;
}

const agentInvocationSchema: OpenAPIV3.SchemaObject = {
  type: "object",
  additionalProperties: false,
  properties: {
    prompt: {
      type: "string",
      description: "Plain-text prompt forwarded to the agent.",
    },
    messages: {
      type: "array",
      description: "Chat-style payload forwarded to the agent.",
      items: {
        type: "object",
        required: ["role", "content"],
        properties: {
          role: {
            type: "string",
            enum: ["user", "assistant", "system", "tool"],
          },
          content: {
            oneOf: [
              { type: "string" },
              {
                type: "array",
                items: {
                  type: "object",
                  required: ["type", "text"],
                  properties: {
                    type: { type: "string" },
                    text: { type: "string" },
                  },
                  additionalProperties: true,
                },
              },
            ],
          },
        },
        additionalProperties: true,
      },
    },
    metadata: {
      type: "object",
      description: "Optional metadata forwarded verbatim to the agent.",
      additionalProperties: true,
    },
  },
  anyOf: [
    { required: ["prompt"] },
    { required: ["messages"] },
  ],
};

const workflowRunRequestSchema: OpenAPIV3.SchemaObject = {
  type: "object",
  required: ["inputData"],
  properties: {
    inputData: {
      type: "object",
      description: "Opaque payload forwarded as workflow inputData.",
      additionalProperties: true,
    },
    metadata: {
      type: "object",
      nullable: true,
      description: "Optional metadata merged into the workflow run.",
      additionalProperties: true,
    },
  },
  additionalProperties: false,
};

const workflowRunResponseSchema: OpenAPIV3.SchemaObject = {
  type: "object",
  required: ["runId", "status"],
  properties: {
    runId: { type: "string", description: "Unique workflow run identifier." },
    status: {
      type: "string",
      description: "Current run status (success, waiting_human, error, etc).",
    },
    result: {
      type: "object",
      description: "Workflow result payload when available.",
      additionalProperties: true,
    },
    pendingHuman: {
      type: "object",
      nullable: true,
      description: "Metadata about the waiting human step when applicable.",
      additionalProperties: true,
    },
    steps: {
      type: "object",
      description: "Scratchpad containing intermediate step data.",
      additionalProperties: true,
    },
    metadata: {
      type: "object",
      description: "Metadata returned by the workflow run.",
      additionalProperties: true,
    },
    startedAt: {
      type: "string",
      format: "date-time",
    },
    finishedAt: {
      type: "string",
      format: "date-time",
      nullable: true,
    },
  },
  additionalProperties: true,
};

const workflowResumeRequestSchema: OpenAPIV3.SchemaObject = {
  type: "object",
  required: ["stepId", "data"],
  properties: {
    stepId: {
      type: "string",
      description: "Identifier of the human step awaiting input.",
    },
    data: {
      type: "object",
      description: "Opaque payload forwarded back to the workflow.",
      additionalProperties: true,
    },
  },
  additionalProperties: false,
};

const sseEventSchema: OpenAPIV3.SchemaObject = {
  type: "object",
  description: "Server-Sent Event envelope emitted by streaming endpoints.",
  properties: {
    event: { type: "string" },
    data: { type: "object", additionalProperties: true },
  },
  additionalProperties: true,
};

const notFoundResponse: OpenAPIV3.ResponseObject = {
  description: "Resource not found.",
  content: {
    "application/json": {
      schema: {
        type: "object",
        properties: {
          error: { type: "string" },
        },
      },
    },
  },
};

const validationErrorResponse: OpenAPIV3.ResponseObject = {
  description: "Validation error",
  content: {
    "application/json": {
      schema: {
        type: "object",
        properties: {
          error: { type: "string" },
        },
      },
    },
  },
};

export function buildOpenAPIDocument(config: SwaggerDocumentConfig): OpenAPIV3.Document {
  return {
    openapi: "3.0.3",
    info: {
      title: config.title,
      version: config.version,
      description: config.description ?? "Autogenerated reference for AI Kit Server endpoints.",
    },
    servers: [{ url: "/" }],
    tags: [
      { name: "Agents", description: "Interact with registered agents." },
      { name: "Workflows", description: "Manage workflow runs." },
    ],
    paths: {
      "/api/agents/{id}/generate": {
        post: {
          tags: ["Agents"],
          summary: "Invoke an agent synchronously.",
          parameters: [
            {
              name: "id",
              in: "path",
              required: true,
              description: "Agent identifier configured in ServerKit.",
              schema: { type: "string" },
            },
          ],
          requestBody: {
            required: true,
            content: {
              "application/json": { schema: agentInvocationSchema },
            },
          },
          responses: {
            200: {
              description: "Agent execution result.",
              content: {
                "application/json": {
                  schema: {
                    type: "object",
                    additionalProperties: true,
                  },
                },
              },
            },
            400: validationErrorResponse,
            404: notFoundResponse,
          },
        },
      },
      "/api/agents/{id}/stream": {
        post: {
          tags: ["Agents"],
          summary: "Stream an agent response.",
          parameters: [
            {
              name: "id",
              in: "path",
              required: true,
              schema: { type: "string" },
            },
          ],
          requestBody: {
            required: true,
            content: {
              "application/json": { schema: agentInvocationSchema },
            },
          },
          responses: {
            200: {
              description: "Server-Sent Events stream.",
              content: {
                "text/event-stream": { schema: sseEventSchema },
              },
            },
            400: validationErrorResponse,
            404: notFoundResponse,
          },
        },
      },
      "/api/workflows/{id}/run": {
        post: {
          tags: ["Workflows"],
          summary: "Execute a workflow run to completion.",
          parameters: [
            {
              name: "id",
              in: "path",
              required: true,
              schema: { type: "string" },
            },
          ],
          requestBody: {
            required: true,
            content: {
              "application/json": { schema: workflowRunRequestSchema },
            },
          },
          responses: {
            200: {
              description: "Workflow run result.",
              content: {
                "application/json": { schema: workflowRunResponseSchema },
              },
            },
            400: validationErrorResponse,
            404: notFoundResponse,
          },
        },
      },
      "/api/workflows/{id}/stream": {
        post: {
          tags: ["Workflows"],
          summary: "Stream workflow run events.",
          parameters: [
            {
              name: "id",
              in: "path",
              required: true,
              schema: { type: "string" },
            },
          ],
          requestBody: {
            required: true,
            content: {
              "application/json": { schema: workflowRunRequestSchema },
            },
          },
          responses: {
            200: {
              description: "Server-Sent Events stream of workflow progress.",
              content: {
                "text/event-stream": { schema: sseEventSchema },
              },
            },
            400: validationErrorResponse,
            404: notFoundResponse,
          },
        },
      },
      "/api/workflows/{id}/runs/{runId}/resume": {
        post: {
          tags: ["Workflows"],
          summary: "Resume a workflow run awaiting human input.",
          parameters: [
            {
              name: "id",
              in: "path",
              required: true,
              schema: { type: "string" },
            },
            {
              name: "runId",
              in: "path",
              required: true,
              schema: { type: "string" },
            },
          ],
          requestBody: {
            required: true,
            content: {
              "application/json": { schema: workflowResumeRequestSchema },
            },
          },
          responses: {
            200: {
              description: "Updated workflow run details.",
              content: {
                "application/json": { schema: workflowRunResponseSchema },
              },
            },
            400: validationErrorResponse,
            404: notFoundResponse,
          },
        },
      },
    },
    components: {
      schemas: {
        AgentInvocation: agentInvocationSchema,
        WorkflowRunRequest: workflowRunRequestSchema,
        WorkflowRunResponse: workflowRunResponseSchema,
        WorkflowResumeRequest: workflowResumeRequestSchema,
        ServerSentEvent: sseEventSchema,
      },
      responses: {
        NotFound: notFoundResponse,
        ValidationError: validationErrorResponse,
      },
    },
  };
}
